; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf, arduino

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_FREERTOS_HZ=1000

monitor_speed = 115200
upload_speed = 921600
